export const customers = [
    {
        id: 1,
        name: 'John Doe',
        email: 'jhondeo@demo.com',
        phone: '1234567890',
        dateOfBirth: '1990-01-01',
        image: '',
        gender: 'male',
        address: {
            street: '123, Main Street',
            city: 'New York',
            zip: '10001',
            state: 'NY',
        },
    },
    {
        id: 2,
        name: 'John Doe',
        email: 'jhondeo@demo.com',
        phone: '1234567890',
        dateOfBirth: '1990-01-01',
        image: '',
        gender: 'male',
        address: {
            street: '123, Main Street',
            city: 'New York',
            zip: '10001',
            state: 'NY',
        },
    },
    {
        id: 3,
        name: 'John Doe',
        email: 'jhondeo@demo.com',
        phone: '1234567890',
        dateOfBirth: '1990-01-01',
        image: '',
        gender: 'male',
        address: {
            street: '123, Main Street',
            city: 'New York',
            zip: '10001',
            state: 'NY',
        },
    },
    {
        id: 4,
        name: 'John Doe',
        email: 'jhondeo@demo.com',
        phone: '1234567890',
        dateOfBirth: '1990-01-01',
        image: '',
        gender: 'male',
        address: {
            street: '123, Main Street',
            city: 'New York',
            zip: '10001',
            state: 'NY',
        },
    },
    {
        id: 5,
        name: 'John Doe',
        email: 'jhondeo@demo.com',
        phone: '1234567890',
        dateOfBirth: '1990-01-01',
        image: '',
        gender: 'male',
        address: {
            street: '123, Main Street',
            city: 'New York',
            zip: '10001',
            state: 'NY',
        },
    },
    {
        id: 6,
        name: 'John Doe',
        email: 'jhondeo@demo.com',
        phone: '1234567890',
        dateOfBirth: '1990-01-01',
        image: '',
        gender: 'male',
        address: {
            street: '123, Main Street',
            city: 'New York',
            zip: '10001',
            state: 'NY',
        },
    },
    {
        id: 7,
        name: 'John Doe',
        email: 'jhondeo@demo.com',
        phone: '1234567890',
        dateOfBirth: '1990-01-01',
        image: '',
        gender: 'male',
        address: {
            street: '123, Main Street',
            city: 'New York',
            zip: '10001',
            state: 'NY',
        },
    },
    {
        id: 8,
        name: 'John Doe',
        email: 'jhondeo@demo.com',
        phone: '1234567890',
        dateOfBirth: '1990-01-01',
        image: '',
        gender: 'male',
        address: {
            street: '123, Main Street',
            city: 'New York',
            zip: '10001',
            state: 'NY',
        },
    },
    {
        id: 9,
        name: 'John Doe',
        email: 'jhondeo@demo.com',
        phone: '1234567890',
        dateOfBirth: '1990-01-01',
        image: '',
        gender: 'male',
        address: {
            street: '123, Main Street',
            city: 'New York',
            zip: '10001',
            state: 'NY',
        },
    },
    {
        id: 10,
        name: 'John Doe',
        email: 'jhondeo@demo.com',
        phone: '1234567890',
        dateOfBirth: '1990-01-01',
        image: '',
        gender: 'male',
        address: {
            street: '123, Main Street',
            city: 'New York',
            zip: '10001',
            state: 'NY',
        },
    },
    {
        id: 11,
        name: 'John Doe',
        email: 'jhondeo@demo.com',
        phone: '1234567890',
        dateOfBirth: '1990-01-01',
        image: '',
        gender: 'male',
        address: {
            street: '123, Main Street',
            city: 'New York',
            zip: '10001',
            state: 'NY',
        },
    },
    {
        id: 12,
        name: 'John Doe',
        email: 'jhondeo@demo.com',
        phone: '1234567890',
        dateOfBirth: '1990-01-01',
        image: '',
        gender: 'male',
        address: {
            street: '123, Main Street',
            city: 'New York',
            zip: '10001',
            state: 'NY',
        },
    },
    {
        id: 13,
        name: 'John Doe',
        email: 'jhondeo@demo.com',
        phone: '1234567890',
        dateOfBirth: '1990-01-01',
        image: '',
        gender: 'male',
        address: {
            street: '123, Main Street',
            city: 'New York',
            zip: '10001',
            state: 'NY',
        },
    },
    {
        id: 14,
        name: 'John Doe',
        email: 'jhondeo@demo.com',
        phone: '1234567890',
        dateOfBirth: '1990-01-01',
        image: '',
        gender: 'male',
        address: {
            street: '123, Main Street',
            city: 'New York',
            zip: '10001',
            state: 'NY',
        },
    },
    {
        id: 15,
        name: 'John Doe',
        email: 'jhondeo@demo.com',
        phone: '1234567890',
        dateOfBirth: '1990-01-01',
        image: '',
        gender: 'male',
        address: {
            street: '123, Main Street',
            city: 'New York',
            zip: '10001',
            state: 'NY',
        },
    },
];
