import Head from 'next/head';
import Layout from '../components/Layout/Layout';
import React from 'react';
import Hero from '../sections/Hero';
import Products from '../sections/Products';

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <React.Fragment>
                    <Hero />
                    <Products heading="Men's Fations" />

                    {/* <Banner src="/banner-1.jpg" alt="banner" /> */}
                    <Products heading="Women's Fations" />
                </React.Fragment>
            </Layout>
        </>
    );
}
